// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHoe56j5IUiEscgxsHZ6VWpkymVwnAYKM',
    appId: '1:912934662928:web:19aa1fe321fcb3b165eb95',
    messagingSenderId: '912934662928',
    projectId: 'blackcoffer-943a0',
    authDomain: 'blackcoffer-943a0.firebaseapp.com',
    storageBucket: 'blackcoffer-943a0.appspot.com',
    measurementId: 'G-YG1HRYZ62Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2wFeE3qhJhIgcCejXeztmrSqvpA_HNTo',
    appId: '1:912934662928:android:d5cabad00662533e65eb95',
    messagingSenderId: '912934662928',
    projectId: 'blackcoffer-943a0',
    storageBucket: 'blackcoffer-943a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNOujbzXuRbaQ8byfs-DDzMvvm_ODFRE',
    appId: '1:912934662928:ios:c539bcfa31f5e05d65eb95',
    messagingSenderId: '912934662928',
    projectId: 'blackcoffer-943a0',
    storageBucket: 'blackcoffer-943a0.appspot.com',
    iosBundleId: 'com.example.blackcoffer',
  );
}
